language: generic
script: "./scripts/compose.sh"
deploy:
  provider: releases
  api_key:
    secure: qIT5OSuAAvymQNPWEGDbb9ogHQVz0udk2qQbL1VDFiafvHP1QyQyesI1IloOOdhdZ0J390755JkB5pG5n5GyM4oiLK6bvHZwXwku2gx2i5o47FHoHa6Hsz6MHqGoqPJlXGNKYSB8Ih9+9sqRHXhppoGM4p4htWrufJwtMQUIRxofsd/5LqLOqTKN9PK5KQVu1+xFb6lJ/4buYYhdLF8ugrs3g0wiFKvDZ1mmBb8bGlSG71Hd6seaF4ETwM8VFUE3sR7mBkbrARoDNltHePKRTl2xKIgFyt0y1kSFAAIwXgAq1ZMz/dYlDqz2V4WPd243+t2vv+xwXWB0N6NvBfaS78QFHX9+tm1K1jLk2AqhMJM55SiqFtY68rUQ+sHlXcpWOSCp0JxfjevMhtWqKaqm56lide8+32Q//GXh0PleH5tZ7xCYWxmJAj40ybMVuGkLFpv5TQa/5C+UZQ+mFojpCfuLu/z6gy44f7ILVfw0M9iXPkcB3CRSN7jBy6QmiroSMRir79fEfwvnJAdwhd9LJ9hbv3nkO+HgBlFE9pN8B6MnURRtPyTdDrFe/h87dgO4YR8g72O7ERnQc9W4t4pKdjJbvW4g+1flwpyriqLaHGd2UtkBNa/owqG8qeWGsC116NPCw4Ym6lBnvMHKa0rJJW0SGVz23q7jpygGWtPWi/o=
  file: target/kamp-eclipse-inst-32.exe
  on:
    repo: MartinLoeper/KAMP-Windows-32bit-Installer
